version: "3.9"

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - 8000:8000

  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"

volumes:
  redis_data: