# Generated by Django 4.2.5 on 2023-11-13 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='text_1',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
