# Generated by Django 4.2.5 on 2023-12-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='chat_id',
            field=models.IntegerField(unique=True),
        ),
    ]
